site_name: SUSTech CS Notes
site_url: https://csnotes.benx.dev
site_author: Ben Chen
site_description:
  Course Notes for the Computer Science @SUSTech.

repo_name: chanbengz/sustech-notes
repo_url: https://github.com/chanbengz/sustech-notes
edit_uri: blob/main/docs/

copyright: Copyright &copy; 2023 - 2024 Ben Chen

theme:
  name: material
  favicon: assets/favicon.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Basis:
    - CS109 Java A: basis/CS109.md
    - CS201 Discrete Math: basis/CS201.md
    - CS202 Computer Organization: basis/CS202.md
    - CS203 Data Structure and Algorithm Analysis: basis/CS203.md
    - CS207 Digital Design: basis/CS207.md
    - CS208 Algorithm Design and Analysis: basis/CS208.md
    - CS307 Database System: basis/CS307.md
  - Core:
    - CS302 Operating System: core/CS302.md
    - CS303 Artificial Intelligence: core/CS303.md
    - CS305 Computer Networks: core/CS305.md
    - CS321 Group Projecg I: core/CS321.md
  - Elective:
    - CS104 Mathematical Logic: elective/CS104.md
    - CS301 Embedded System and Microcomputer Principle: elective/CS301.md
    - CS309 Object-Oriented Analysis and Design: elective/CS309.md
    - CS323 Compilers: elective/CS323.md
    - CSE5014 Cryptography: elective/CSE5014.md
  - Other:
    - SS149 Early Modern Western Philosophy: other/SS149.md
    - NUS SOC Summer Workshop: other/SWS.md
  - Tools:
    - tools/git.md
    - tools/markdown.md
    - tools/latex.md
    - tools/linux.md
    - tools/docker.md
  - Blog: https://blog.benx.dev


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Basis: 专业基础课
            Core: 专业核心课
            Elective: 专业选修课
            Other: 其他
            Tools: 实用工具
            CS104 Mathematical Logic: CS104 数理逻辑导论
            CS109 Java A: CS109 计算机程序设计基础
            CS201 Discrete Math: CS201 离散数学
            CS202 Computer Organization: CS202 计算机组成原理
            CS203 Data Structure and Algorithm Analysis: CS203 数据结构与算法分析
            CS207 Digital Design: CS207 数字逻辑
            CS208 Algorithm Design and Analysis: CS208 算法设计与分析
            CS301 Embedded System and Microcomputer Principle: CS301 嵌入式与微机原理
            CS302 Operating System: CS302 操作系统
            CS303 Artificial Intelligence: CS303 人工智能
            CS305 Computer Networks: CS305 计算机网络
            CS307 Database System: CS307 数据库
            CS321 Group Projecg I: CS321 创新实践1
            CSE5014 Cryptography: CSE5014 密码学与网络安全
            NUS SOC Summer Workshop: NUS SOC 夏令营

  - search:
      lang:
        - zh
        - en
